/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class app_JNI_CLibrary */

#ifndef _Included_app_JNI_CLibrary
#define _Included_app_JNI_CLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     app_JNI_CLibrary
 * Method:    enumWindows
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_app_JNI_CLibrary_enumWindows
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
